os:
  - linux
  - osx

osx_image: xcode10.1

language: node_js

node_js:
  - '11.10'

cache:
  - npm
  - yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - travis_retry yarn install
  - travis_retry yarn lerna bootstrap

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi

script:
  - git diff --exit-code yarn.lock
  - yarn build
  - yarn test
